upstream employee-fe {
    server employee-fe:8000;
}

upstream employer-fe {
    server employer-fe:8001;
}

upstream clock-fe {
    server clock-fe:8002;
}

upstream backend {
    server backend:3000;
}

upstream images {
    server images:3001;
}

server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location / {
        proxy_pass http://employee-fe/;
    }

    location /management/ {
        proxy_pass http://employer-fe/;
    }

    location /clock/ {
        proxy_pass http://clock-fe/;
    }

    location /api/ {
        proxy_pass http://backend/;
    }

    location /images/ {
        proxy_pass http://images/;
    }

}